# Generated by Django 6.0.7 on 2026-08-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="slug",
            field=models.SlugField(default="test"),
            preserve_default=False,
        ),
    ]
